# =================================================================
# Docker Compose Override for Development Environment
# =================================================================
# This file automatically extends docker-compose.yml for development
# It enables debug features, verbose logging, and development tools

services:
  # Development overrides for Keycloak
  keycloak:
    command:
      - start-dev
      - --import-realm
      - --http-relative-path=/auth
      - --hostname-strict=false
      - --log=console
      - --log-level=debug,jakarta.ws:info,org.keycloak:debug,org.keycloak.events:debug,org.keycloak.services:debug,org.keycloak.authentication:debug,org.keycloak.protocol:debug,org.keycloak.broker:debug,com.example:debug
    environment:
      # Override for development
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      
      # JVM debug options
      JAVA_OPTS_APPEND: >-
        -XX:+UseG1GC
        -XX:+UseStringDeduplication
        -Xms256m
        -Xmx512m
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
        -Djava.awt.headless=true
    ports:
      - "8081:8080"
      - "8787:8787"  # JVM debug port
    
  # Development overrides for APIs
  aceas-api:
    environment:
      NODE_ENV: development
      DEBUG: "*"
      LOG_LEVEL: debug
    command: ["npm", "start"]
    
  cpds-api:
    environment:
      NODE_ENV: development
      DEBUG: "*"
      LOG_LEVEL: debug
    command: ["npm", "start"]
    
  ids:
    environment:
      NODE_ENV: development
      DEBUG: "*"
      LOG_LEVEL: debug
    command: ["npm", "start"]
    
  mockpass:
    environment:
      NODE_ENV: development
      DEBUG: "*"
      LOG_LEVEL: debug

  # Development overrides for nginx
  web:
    volumes:
      # Add development-specific nginx config
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/dev.conf:ro
    environment:
      NGINX_LOG_LEVEL: debug
