const s=document.getElementById("spaceCanvas"),i=s.getContext("2d");function m(){s.width=window.innerWidth,s.height=window.innerHeight}m();window.addEventListener("resize",m);const y=[];for(let t=0;t<200;t++)y.push({x:Math.random()*s.width,y:Math.random()*s.height,radius:Math.random()*1.5,opacity:Math.random()*.5+.5,twinkleSpeed:Math.random()*.02+.01,twinklePhase:Math.random()*Math.PI*2});const f=[];for(let t=0;t<50;t++)f.push({x:Math.random()*s.width,y:Math.random()*s.height,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3,radius:Math.random()*100+50,color:["rgba(100, 150, 255, 0.1)","rgba(80, 120, 255, 0.08)","rgba(120, 160, 255, 0.12)"][Math.floor(Math.random()*3)]});let a=0;function w(){i.fillStyle="rgba(13, 20, 40, 0.95)",i.fillRect(0,0,s.width,s.height),f.forEach(t=>{t.x+=t.vx,t.y+=t.vy,t.x<-t.radius&&(t.x=s.width+t.radius),t.x>s.width+t.radius&&(t.x=-t.radius),t.y<-t.radius&&(t.y=s.height+t.radius),t.y>s.height+t.radius&&(t.y=-t.radius);const e=i.createRadialGradient(t.x,t.y,0,t.x,t.y,t.radius);e.addColorStop(0,t.color),e.addColorStop(1,"rgba(100, 150, 255, 0)"),i.fillStyle=e,i.fillRect(t.x-t.radius,t.y-t.radius,t.radius*2,t.radius*2)}),y.forEach(t=>{t.twinklePhase+=t.twinkleSpeed;const e=Math.sin(t.twinklePhase)*.3+.7;i.fillStyle=`rgba(255, 255, 255, ${t.opacity*e})`,i.beginPath(),i.arc(t.x,t.y,t.radius,0,Math.PI*2),i.fill(),t.radius>1&&(i.strokeStyle=`rgba(100, 150, 255, ${t.opacity*e*.5})`,i.lineWidth=1,i.beginPath(),i.arc(t.x,t.y,t.radius+2,0,Math.PI*2),i.stroke())}),a+=.01;for(let t=0;t<30;t++){const e=Math.sin(a*.5+t)*s.width/2+s.width/2,o=Math.cos(a*.3+t*.5)*s.height/2+s.height/2,n=Math.sin(a+t)*1+1.5;i.fillStyle=`rgba(100, 150, 255, ${Math.sin(a+t)*.3+.3})`,i.beginPath(),i.arc(e,o,n,0,Math.PI*2),i.fill()}requestAnimationFrame(w)}w();const l=document.getElementById("cardWrapper");document.addEventListener("mousemove",t=>{const e=l.getBoundingClientRect(),o=e.left+e.width/2,n=e.top+e.height/2,c=(t.clientY-n)/25,h=(t.clientX-o)/25;l.style.transform=`rotateX(${-c}deg) rotateY(${h}deg)`});document.addEventListener("mouseleave",()=>{l.style.transform="rotateX(0deg) rotateY(0deg)"});const p=document.getElementById("password"),g=document.getElementById("passwordToggle");g.addEventListener("click",t=>{t.preventDefault();const e=p.type==="password";p.type=e?"text":"password";const o=g.querySelector("svg");e?o.innerHTML=`
            <path d="M2 2l20 20M5.3 5.3C1.5 8 1 12 1 12s4-8 11-8c1.9 0 3.5.4 5 1l-1.7 1.7"></path>
            <path d="M9.3 9.3C8.5 10 8 11 8 12c0 2.2 1.8 4 4 4 1 0 2-.5 2.7-1.3"></path>
            <path d="M15 15.5c-2.1.7-4.3 1-6.5.5-5.5-1-8.5-7-8.5-7s1.1-2.2 3.3-4.3"></path>
        `:o.innerHTML=`
            <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
            <circle cx="12" cy="12" r="3"></circle>
        `});const E=document.getElementById("kc-form-login"),r=document.getElementById("kc-login");E.addEventListener("submit",async t=>{r.disabled=!0,r.innerHTML='<span class="spinner"></span>Signing in...',await new Promise(e=>setTimeout(e,1500)),r.disabled=!1,r.innerHTML="Sign In"});function M(t){t.addEventListener("click",e=>{const o=t.getBoundingClientRect(),n=Math.max(o.width,o.height),c=e.clientX-o.left-n/2,h=e.clientY-o.top-n/2,d=document.createElement("div");d.className="ripple",d.style.width=d.style.height=n+"px",d.style.left=c+"px",d.style.top=h+"px",t.appendChild(d),setTimeout(()=>d.remove(),600)})}const v=document.getElementById("social-mockpass-singpass"),x=document.getElementById("social-mockpass-corppass");M(v);M(x);v.addEventListener("click",()=>{});x.addEventListener("click",()=>{});
//# sourceMappingURL=index.js.map
